version: 2
updates:
  - package-ecosystem: "docker"
    directory: "docker/php/8.1"
    schedule:
      interval: "weekly"
    assignees:
      - "matthewhartstonge"
    ignore:
      - dependency-name: "php"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "docker/php/8.2"
    schedule:
      interval: "weekly"
    assignees:
      - "matthewhartstonge"
    ignore:
      - dependency-name: "php"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "docker/php/8.3"
    schedule:
      interval: "weekly"
    assignees:
      - "matthewhartstonge"
    ignore:
      - dependency-name: "php"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "docker/php/8.4"
    schedule:
      interval: "weekly"
    assignees:
      - "matthewhartstonge"
    ignore:
      - dependency-name: "php"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
