version: "3.7"

networks:
  mysql:
  php:
  varnish:

services:
  nginx:
    image: nginx:stable-alpine
    networks:
      - php
      - varnish
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/varnish.conf:/etc/nginx/conf.d/default.conf

  varnish:
    image: varnish:stable
    networks:
      - varnish
    tmpfs:
      - /usr/local/var/varnish:exec
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro

  php-fpm:
    # Uncomment the build context in order to build with any changes made
    # to the docker file.
    #build:
    #  context: ../docker/php/7.2
    image: matthewhartstonge/stackme-php7-fpm:7.2
    networks:
      - mysql
      - php
    volumes:
      #- ../docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../docker/php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
      - ./logs/php:/logs

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: super_secret_password
      MYSQL_DATABASE: secret_db
      MYSQL_USER: secret_user
      MYSQL_PASSWORD: secret_user_password
    networks:
      - mysql
    # Uncomment the ports block if you want to connect to the database locally.
    #ports:
    #  - "3306:3306"
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
      # import a mysqldump backup. Make sure to edit the file and add USE your_db;
      # At the top of the script. After importing, due to the persistent folder
      # mapping, you can comment out the mapping below.
      #- ./dbdata/backup.sql:/docker-entrypoint-initdb.d/mysql.sql
